config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :attendances
      resources :events

      root to: "users#index"
    end
  resources :charges

  resources :admins, only: [:index] do
    resources :users
    root 'admins#index'
  end
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index, :new, :create]
  end
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
require 'time'
class Event < ApplicationRecord
    
    belongs_to :user
    has_many :attendances
    has_many :users, through: :attendances

    # Validations

    validates :start_date, presence: true, if: :not_in_past?
    validates :duration, numericality: { greater_than: 0, only_integer: true }, if: :multipe_of_5?
    validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
    validates :title, presence: true, length: { minimum: 5, maximum: 140 }
    validates :price, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 1000, only_integer: true }
    validates :location, presence: true

    def not_in_past?
        start_date > Time.now
    end

    def multipe_of_5?
        duration % 5 == 0
    end
    
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new]
  before_action :only_admin_own_event, only: [:edit, :update, :destroy]

  
  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    puts "=" * 50
    puts "voici les params"
    puts params
    puts "=" * 50
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
    @event = Event.new(user_id: current_user.id, start_date: date, duration: params[:duration].to_i, title: params[:title], description: params[:description], price: params[:price].to_i, location: params[:location])
    if @event.save!
      redirect_to root_url
    else 
      redirect_to new_event_url
    end
  end


  def show
    @event = Event.find(params[:id])
    @creator = User.find(@event.user_id)
    if user_signed_in?
      @attendance = Attendance.find_by(event_id: params[:id], user_id: current_user.id)
    end
  end


  def edit
    @event = Event.find(params[:id])
  end


  def update
    @event = Event.find(params[:id])
    date = Date.new(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
    if @event.update(user_id: current_user.id, start_date: date, duration: params[:duration].to_i, title: params[:title], description: params[:description], price: params[:event][:price], location: params[:location])
      redirect_to event_path(@event.id)
    else
      redirect_to edit_event_path(@event.id)
    end
  end


  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end


  def only_admin_own_event
    @event = Event.find(params[:id])
  
    if @event.user_id != current_user.id
      redirect_to root_path, notice: "Sorry, but you are not allowed to access this page"
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<body>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" style="background-image: url('https://images.unsplash.com/photo-1500964757637-c85e8a162699?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=778&q=80'); background-repeat: no-repeat; background-size: cover;">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 font-weight-normal" style="font-family: OCR A Std, monospace; color:#00478E;">The Events Organisation Reference</h1></h1>
            <p class="lead font-weight-normal" style="font-family: OCR A Std, monospace; color:#00478E;">Plan, Set-up, Organise, Remind people, and Master any kind of Events</p>
        </div>
    </div>
    <div class="index-title" style="font-family: OCR A Std, monospace; color:#00478E;">
        <h3>Check all the Events near you ! </h3>
    </div>
    <div class="card-deck" style="margin-left: 5%;">
        <%= @event.each do |e| %>
            <div class="card-deck col-sm-4 mb-3">
                <div class="card mb-4 shadow-sm">
                    <div class="card-header"><%= e.title %></div>
                    <div class="card-body text-info">
                        <h4 class="card-title">Price <%= e.price %> $</h4>
                        <p class="card-text"> Where : <%= e.location %></p>
                        <p class="card-text"> About it : <%= e.description %></p>
                        <a href="<%= event_path(e.id) %>" <button type="button" class="btn btn-outline-warning" >Voir plus</button></a>
                        <a href="<%= event_path(e.id) %>" <button type="button" class="btn btn-outline-danger" data-confirm="Are you sure you want to cancel this event?" data-method="DELETE">Cancel Event</button></a>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</body>

app/views/events/new.html.erb
<body>
    <h1 style="font-family: OCR A Std, monospace; color:#00478E;">Create a New event</h1>
    <div style="margin-left: 10%; background-image: url('https://images.unsplash.com/photo-1513128034602-7814ccaddd4e?ixlib=rb-1.2.1&auto=format&fit=crop&w=375&q=80'); background-repeat: no-repeat; background-position: 85% 45%;" align="left">
    <%= form_tag url_for(action: 'create'), method: "POST" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <div class="form-group" style=" margin-right: 80%;">
            <%= label_tag "Name the Event :"%>
            <%= text_field_tag 'title', nil, class: 'form-control'%>
        </div>
        <div class="form-group" style=" margin-right: 85%;">
            <%= label_tag "How much it cost?"%>
            <%= text_field_tag 'price', nil, class: 'form-control'%>
        </div> 
        <div class="form-group" style=" margin-right: 65%;">
            <%= label_tag "About it"%>
            <%= text_area_tag 'description', nil, class: 'form-control'%>
        </div>  
        <div class="form-group" style=" margin-right: 80%;">
            <%= label_tag "When does it begin ?"%>
            <%= select_date Date.today, prefix: :start_date, class: 'form-control"' %>
        </div> 
        <div class="form-group" style=" margin-right: 80%;">
            <%= label_tag "How long it last? (in minutes)"%>
            <%= text_field_tag 'duration', nil, class: 'form-control'%>
        </div> 
        <div class="form-group" style=" margin-right: 70%;">
            <%= label_tag "Where does it take place?"%>
            <%= text_field_tag 'location', nil, class: 'form-control'%>
        </div>  
        <div class="form-group"> 
            <button type="submit" class="btn btn-warning">Create the Event</button>
        </div>  
    <% end %> 
    </div> 
</body>

app/views/events/show.html.erb
<body>
    <div style="color:#3737F4; font-family: Marker Felt, fantasy;">
        <h2>About this Event</h2>
    </div>
        <div class="card" style="width: 50%; margin-left: 25%;">
        <div class="card-header" style="font-family: DejaVu Sans Mono, monospace;">It's Called <%= @event.title %></div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item" style="background-color:#7CC4DE; font-family: DejaVu Sans Mono, monospace;">It starts <%= @event.start_date %></li>
            <li class="list-group-item" style="background-color:#7CDEB0; font-family: DejaVu Sans Mono, monospace;">It happen at/in <%= @event.location %></li>
            <li class="list-group-item" style="background-color:#CDDE7C; font-family: DejaVu Sans Mono, monospace;">About it : <%= @event.description %></li>
        </ul>
        <a href="<%= new_event_attendance_path(@event.id) %>" <button type="button" class="btn btn-outline-succes" >Register for this event</button></a>
        </div>
</body>