config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :attendances
      resources :events

      root to: "users#index"
    end
  resources :charges

  resources :admins, only: [:index] do
    resources :users
    root 'admins#index'
  end
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index, :new, :create]
  end
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    puts "*"*50
    puts "je suis dans 'new'"
    puts "*"*50
    puts params
    puts "*"*5
    puts @amount
    puts "*"*50
  end

  def create
    @event = Event.find(params[:event_id])
    @amount = @event.price
    puts "*"*50
    puts "je suis dans 'create'"
    puts "*"*50
    puts params
    puts "*"*5
    puts @event
    puts "*"*50

   customer = Stripe::Customer.create(
     :email => params[:stripeEmail],
     :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
    
    puts "*"*50
    puts charge[:customer]
    puts "*"*50

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @amount %></strong>!</h2>

app/views/charges/new.htlm.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= @amount %>
          data-locale="auto"></script>
<% end %>