config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :attendances
      resources :events

      root to: "users#index"
    end
  resources :charges

  resources :admins, only: [:index] do
    resources :users
    root 'admins#index'
  end
  root 'events#index'
  resources :events do
    resources :attendances, only: [:index, :new, :create]
  end
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css">
    <title>EventtribeThp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
  </head>

  <body style="background-color: #B98CE5;">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top justify-content-around" style="background-color: #74D6FA;">
      <a class="navbar-brand" style="color:#3737F4; font-family: Marker Felt, fantasy;"href="<%= root_path %>">EVENT.TRIBE.THP</a>
      <a class="py-2 d-none d-md-inline-block" style="color:#3737F4; font-family: Marker Felt, fantasy;" href="<%= new_event_path %>">Create Event</a>
      <ul>
        <% if user_signed_in? %>
          <div style="color:#3737F4; font-family: Marker Felt, fantasy;">
            <a><%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
            <a>Your email is <%= current_user.email %></a>
            <a><%= link_to "Edit email / password", edit_user_registration_path %></a>
          </div>
        <% else %>
            <div class="dropdown show">
              <a class="btn btn-secondary dropdown-toggle" style="color:#54A6F9; background-color:#0D44F9; font-family: Marker Felt, fantasy;" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: #74A3FA; border: none; margin-top: 10px;">
                Sign-in / Sign-up
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%= new_user_session_path %>">Sign in</a>
                <a class="dropdown-item" href="<%= new_user_registration_path %>">Sign up</a>
              </div>
            </div> 
        <% end %>
      </ul>
    </nav>
    <div class="text-center" style="background-color: #B98CE5;">
    <%= yield %>
    </div>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>